version = "Two"
edition = "2018"
newline_style = "Unix"

hard_tabs = true
use_small_heuristics = "Max"
use_try_shorthand = true

# Unstable

where_single_line = true
fn_params_layout = "Compressed"
fn_single_line = true
format_strings = true
overflow_delimited_expr = true
